services:
  web:
    build: .
    command: npm run start:prod
    environment:
      DB_HOST: dpg-d74u1s0ule4c73f9o6u0-a
      DB_PORT: "5432"
      DB_USER: vinyls_fhit_user
      DB_PASS: yrRmFzSJTULMIoNWpyFevAodPposQzR2
      DB_NAME: vinyls_fhit
      USE_SSL: true
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: vinyls
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
